### ISSUE TITLE
Option to add geometry field

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/map-builder#5]
At the moment, I can only add lon and lat fields separately in the map builder form. I don't have an option add geometry field, e.g., such as in CKAN Classic admin site.

Current look of the map builder component:

<img width="262" alt="Screen Shot 2020-03-10 at 18 45 56" src="https://user-images.githubusercontent.com/17809581/76313596-73f77080-62ff-11ea-8f4b-f6a1e55f6e52.png">

## Acceptance criteria

* [x] I can add geometry field

## Tasks

* [x] Add an option to submit geometry field
* [x] Test against fixtures, if needed add a new fixture with geometry field
* [x] Release a new version

## Analysis

TODO

**Comment by sagargg** [comment]
@julietezekwe  we need two-state as given below: 
state 1: User can select  `longitude, latitude` fields where two dropdown select fields will appear as shown on design. 
state 2: User can select the `Geometry` field. " where only one dropdown select field will appear as shown on design.  
Here is the design for better understand. 
![Artboard 1](https://user-images.githubusercontent.com/11631101/76491012-b2eb0a80-6454-11ea-8b1a-dca8002a5476.png)

probably you need to use redux to change the form field according to the checkbox selected.

**Comment by julietezekwe** [comment]
I ge it now, let me try that

**Comment by anuveyatsu** [comment]
Hey @julietezekwe I've merged this already to not complicate it. I'm not sure about suggestions from @sagargg - I'd prefer tabs instead but it might be just me.

**Comment by julietezekwe** [comment]
Oh, Let me try something anyways and show you after standup. If it is better then I can raise another PR

**Comment by julietezekwe** [comment]
@anuveyatsu 

The newly updated `MapBuilder` package is not reflecting in the data-explorer.
- I have installed it and ran `yarn start`
- I opened the `@datopian/map-builder` inside node_modules and I noticed it is still the old version

My Hypothesis
- I think that I am meant to release the package after updating so it can be recorded as updated to another version.
- Kindly advise

**Comment by anuveyatsu** [comment]
Closing this as FIXED - available in v0.1.4 and in data-explorer v0.4.9

@julietezekwe note that the "analysis" section of this issue is empty but it is the starting point normally.
