### ISSUE TITLE
[VULN] Map Builder injection vulnerability

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/map-builder#9]
This issue is moved from gitlab and originally created by @starsinmypockets 

As a User I want to be imune from potential script injection attacks so that I can use and share the Data Explorer securely.

### Acceptence

- [ ] Arbitrary JS code cannot be run on Data Explorer Page

### Tasks

- [ ] Analyse injection vuln
- [ ] Mitigate injection vuln

### Analysis

![Screen_Shot_2019-09-11_at_12.40.01_PM](/uploads/d22f44fda52ecbbb022e9382fbba7ee9/Screen_Shot_2019-09-11_at_12.40.01_PM.png)

See here for further explanation of this attack vector: https://checkmarx.gitbooks.io/js-scp/output-encoding/cross-site-scripting/how-to-prevent.html
